COMMON: &common
  DEBUG: False
  TESTING: False
  SECRET_KEY: YouShouldNeverGuessWithIt
  # Logger
  LOGGER_ENABLED: True
  LOGGER_LEVEL: DEBUG
  LOGGER_FORMAT: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
  LOGGER_DATE_FORMAT: '%m-%d %H:%M:%S'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: False
  TESTING: False

TESTING: &testing
  <<: *common
  TESTING: True